FROM golang:$GO_VERSION AS build
WORKDIR /go/src/app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags='-s -w' -o /go/bin/app -trimpath

FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=build /go/bin/app /
CMD ["/app"]
